### ISSUE TITLE
Consider adding a dark mode (or custom themeing)

### ISSUE THREAD

**Issue by juliusv** [promlabs/promlens-public#5]
Currently PromLens's CSS styling is hardcoded. Consider making introducing the option for a dark mode or even themeing.

**Comment by baryluk** [comment]
Would be nice indeed. Almost all tools I use today have dark mode.

Modern browser support CSS to do this:

```html
<meta name="color-scheme" content="dark light">
<link href="https://cdn.jsdelivr.net/npm/bootstrap-dark-5@1.1.3/dist/css/bootstrap-night.min.css" rel="stylesheet" media="(prefers-color-scheme: dark)" referrerpolicy="strict-origin" crossorigin="anonymous">
<link href="https://cdn.jsdelivr.net/npm/bootstrap-dark-5@1.1.3/dist/css/bootstrap.min.css" rel="stylesheet" media="(prefers-color-scheme: light)" referrerpolicy="strict-origin" crossorigin="anonymous">
```

the above is nice, as only one css is downloaded initially. alternatively both color schemes can be shipped inside one css, and selectors marked propely:

```css
  body, select, input, textarea {color: #333;}

  a {color: #03f;}
  a:hover {color: #69f;}

  @media (prefers-color-scheme: dark) {
    body {background-color: #222;}
    body, select, input, textarea {color: #aaa;}
    a {color: #557392;}
    a:hover {color: #557392;}
  }

....
```


`media="(prefers-color-scheme: light)"` can also be used in `<source>` tag inside `<picture>`:

```html
<picture>
<source srcset="log_dark.png" media="(prefers-color-scheme:dark)">
<img src="logo_light.png" width=64 height=64>
</picture>
```
